title: Terrassevin
description: >
  Garageimportør med speciale i lavinterventionsvine fra Østeuropa m.fl.
baseurl: ""
url: "https://terrassevin.dk"
paginate:	2 # The number of posts to show per page on your homepage
paginate_path: "/blog/page:num/"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
collections:
  wineries:
    output: true
  people:
logo: "/assets/images/logo.csv"
